"""add tables back

Revision ID: 17e5588afced
Revises: 672489567d33
Create Date: 2023-12-06 15:12:54.805095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e5588afced'
down_revision: Union[str, None] = '672489567d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('username', sa.String, primary_key=True, index=True),
        sa.Column('password', sa.String),
        sa.Column('email', sa.String),
        sa.Column('phone_number', sa.String),
        sa.Column('user_id', sa.Integer, index=True, autoincrement=True, unique=True, primary_key=True),
        sa.UniqueConstraint('username', 'password', name='uq_username_password')
    )

    # Create 'songs' table
    op.create_table('songs',
        sa.Column('song_file', sa.String, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.user_id')),
        sa.Column('song_id', sa.Integer, autoincrement=True, unique=True, primary_key=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
